### ISSUE TITLE
BLOOMZ generates the questions and can enter a monologue loop

### ISSUE THREAD

**Issue by Vincent-Stragier** [petals-infra/chat.petals.dev#10]
Hi,

I've played a little with the chatbot this morning, and I got it stuck in a monologue for a few exchanges:

[image](https://user-images.githubusercontent.com/28227183/215738003-aa69ad47-2c8b-42fc-9538-564271b9e0f5.png)

I think the expected behaviour would be to stop the text generation when ` Human: ` appears in the generated output. However, this might lead to premature stop (maybe there should be an option to overwrite the stop and continue if a ` Human: ` is detected).

**Comment by vadi2** [comment]
Also just some extra information, it looks like `</s>` is the stop parameter for bloom.

**Comment by DarkIlluminatus** [comment]
Define a role for the model in the first prompt.

```You are PepeAI, a Large Language Model trained on BLOOMZ.``` 
add detail if you like. Then add (in the same prompt):
```
User:  This is an example prompt
PepeAI: Hey there, I see you are explaining prompts right now, how can I help?
```
try that out.

**Comment by Vincent-Stragier** [comment]
I did not try it on BLOOMZ, but it may work. However, with Llama2, it makes more sense to use this newer model. Thanks for your help.
