### ISSUE TITLE
Change separators for BLOOMZ in the few-shot mode

### ISSUE THREAD

**Issue by borzunov** [petals-infra/chat.petals.dev#14]
Currently, BLOOMZ behaves well only for the first output in the few-shot mode, then outputs `</s>` and forgets everything. This is visible in the English-to-Spanish translation example.

We need to use `stop_sequence = "\n\n"` and `extra_stop_sequences = ["</s>"]` to fix this.

**Comment by DarkIlluminatus** [comment]
good idea.

**Comment by borzunov** [comment]
Few-shot mode was removed, since we decided to focus on supporting multiple model families instead.
