### ISSUE TITLE
Open ports needed to connect to the public petals cluster?

### ISSUE THREAD

**Issue by sblaszak** [petals-infra/chat.petals.dev#15]
Are there specific network ports that need to be open on my firewall in order to allow my system to join the public cluster?  If so, which ones?

**Comment by borzunov** [comment]
Hi @sblaszak,

For the chat app, you don't need to open any ports for incoming connections, but you need to allow outgoing TCP connections to any TCP ports (Petals servers may use arbitrary TCP ports + you need to send requests to TCP 80/443 to download model weights from Hugging Face servers).

**Comment by sblaszak** [comment]
Great!  Thanks for the response here and in the main Petals git.
