### ISSUE TITLE
python setup.py bdist_wheel did not run successfully / Failed building wheel for grpcio-tools

### ISSUE THREAD

**Issue by finnishbroccoli** [petals-infra/chat.petals.dev#18]
Linux, Python 3.11.3
installation
git clone https://github.com/borzunov/chat.petals.ml.git
python -m venv /home/mkw/yhteinen/chat.petals.ml
cd chat.petals.ml/
source bin/activate
pip install -r requirements.txt 

I've tried to find a solution on the net, but no luck. A log file attached
[lokitiedosto_2.txt](https://github.com/petals-infra/chat.petals.ml/files/12083905/lokitiedosto_2.txt)

**Comment by borzunov** [comment]
Hi @finnishbroccoli,

Python 3.11 is not supported by all our dependencies yet, can you try Python 3.8 - 3.10?

**Comment by finnishbroccoli** [comment]
Yes, reinstalling python 3.8 solved the problem. Thanks a lot!

**Comment by finnishbroccoli** [comment]
Closing
