### ISSUE TITLE
HTTP API fails

### ISSUE THREAD

**Issue by apcameron** [petals-infra/chat.petals.dev#21]
The HTTP API fails while **the chat option works**

curl http://chat.petals.ml/api/v1/generate  -H "Content-Type: application/x-www-form-urlencoded" -d 'inputs="A cat in French is "&max_new_tokens=3'
{"ok":false,"traceback":"Traceback (most recent call last):\n  File \"/home/borzunov/chat.petals.ml/http_api.py\", line 40, in http_api_generate\n    outputs = model.generate(\n  File \"/home/borzunov/.local/lib/python3.10/site-packages/torch/autograd/grad_mode.py\", line 27, in decorate_context\n    return func(*args, **kwargs)\n  File \"/home/borzunov/.local/lib/python3.10/site-packages/petals/client/remote_generation.py\", line 171, in generate\n    hidden_state = session.step(hidden_state, prompts=intermediate_prompts, hypo_ids=hypo_ids)[:, -1]\n  File \"/home/borzunov/.local/lib/python3.10/site-packages/petals/client/inference_session.py\", line 301, in step\n    self._update_sequence(server_idx, block_idx, attempt_no)\n  File \"/home/borzunov/.local/lib/python3.10/site-packages/petals/client/inference_session.py\", line 343, in _update_sequence\n    updated_spans = self._sequence_manager.make_sequence(\n  File \"/home/borzunov/.local/lib/python3.10/site-packages/petals/client/routing/sequence_manager.py\", line 154, in make_sequence\n    span_sequence = self._make_sequence_with_min_latency(\n  File \"/home/borzunov/.local/lib/python3.10/site-packages/petals/client/routing/sequence_manager.py\", line 182, in _make_sequence_with_min_latency\n    raise MissingBlocksError(missing_blocks)\npetals.client.routing.sequence_manager.MissingBlocksError: No servers holding blocks [0, 1, 2, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42] are online. You can check the public swarm's state at http://health.petals.ml If there are not enough servers, please connect your GPU: https://github.com/bigscience-workshop/petals#connect-your-gpu-and-increase-petals-capacity \n"}

**Comment by borzunov** [comment]
Hi @apcameron,

The API uses `bigscience/bloom` by default, but right now we don't have enough servers to host this model (see [here](http://health.petals.ml)) because everyone hosts LLaMA-65B / Guanaco-65B.

You can specify another model (see the list [here](https://github.com/petals-infra/chat.petals.ml/blob/main/config.py#L17)) and it's gonna work, or connect your own GPUs to host missing BLOOM blocks if you need BLOOM specifically.

Let me know if you have any other issues!
