### ISSUE TITLE
Site not available. 

### ISSUE THREAD

**Issue by gspitman** [petals-infra/chat.petals.dev#22]
I'm getting a DNS resolution error on chat.petals.ml

**Comment by vadi2** [comment]
The following message is on [Discord](https://discord.com/channels/865254854262652969/1048288480293289995/1131511676093595779):

> Hi @everyone! We're having issues with our domain registrar providing petals.ml domain, which became unavailable this night. We're working on fixing them, but may eventually switch to a new domain.
> 
> If you can't connect to public swarm bootstrap peers, please update to Petals 2.0.0.post2. This version contains bootstrap peer IP addresses for a direct connection without DNS name resolution:
> 
> pip install --upgrade petals
> 
> 
> If you'd like to use a chatbot app or a health service, you can use their IP addresses in your browser (see below) or add this to /etc/hosts:
> 
> 185.199.108.153 petals.ml
> 159.223.29.252 bootstrap1.petals.ml
> 24.144.96.147 bootstrap2.petals.ml
> 143.244.175.95 chat.petals.ml
> 24.144.96.147 health.petals.ml
> 
> 
> We apologize for the inconvenience. 
>

**Comment by borzunov** [comment]
Hi @gspitman,

We've moved to a new domain, see https://chat.petals.dev

Let us know if you have any other issues!
