### ISSUE TITLE
OSError: meta-llama/Llama-2-70b-hf is not a local folder and is not a valid model identifier

### ISSUE THREAD

**Issue by Sharpz7** [petals-infra/chat.petals.dev#35]
Hey folks, I am trying to run the chat locally, on a system without a GPU. The first issue I have ran into is:

```
OSError: meta-llama/Llama-2-70b-hf is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.
```

Any suggestions?

**Comment by borzunov** [comment]
Hi @Sharpz7,

First of all, please make sure you have the latest Petals version: `pip install --upgrade petals`

Then, please note that you need a valid access token to download Llama 2 weights, see the **"🦙 Want to run LLaMA 2?"** section at https://github.com/bigscience-workshop/petals#readme.

So you need to:
- Either get the access token (follow instructions at the link above) and run `huggingface-cli login` before starting the chat app.
- Or just remove Llama 2 models from the list of served models in `config.py`.

I'll add these explanations to the repo's readme, sorry for the inconvenience!

**Comment by Sharpz7** [comment]
Also probably worth mentioning that you need to submit a form through meta as well as documented on the huggingface page. https://huggingface.co/meta-llama/Llama-2-70b-hf

Thanks for your help! I would be interested in contributing my changes to this repo upstream if you are open to suggestions :))

**Comment by borzunov** [comment]
Yes, I've updated the readme earlier today to reflect that.

You're welcome to contribute! Feel free to reach out if you have any other issues.

**Comment by Xuanming13** [comment]
> Hi @Sharpz7,
> 
> First of all, please make sure you have the latest Petals version: `pip install --upgrade petals`
> 
> Then, please note that you need a valid access token to download Llama 2 weights, see the **"🦙 Want to run LLaMA 2?"** section at https://github.com/bigscience-workshop/petals#readme.
> 
> So you need to:
> 
> * Either get the access token (follow instructions at the link above) and run `huggingface-cli login` before starting the chat app.
> * Or just remove Llama 2 models from the list of served models in `config.py`.
> 
> I'll add these explanations to the repo's readme, sorry for the inconvenience!

Thank you very much for your first advice. I faced this issue while gaining all needed authorizations. 
"pip install --upgrade petals" is needed and easily ignored. 
Finally made it with this command.
