### ISSUE TITLE
Can I test your http API at http://chat.petals.dev/api1 using curl?

### ISSUE THREAD

**Issue by 621625** [petals-infra/chat.petals.dev#38]
Hi,

I'm Mr. Rushmore, a very friendly guy.

Can I test your http API at http://chat.petals.dev/api1 using curl?

Can you show me an example of the curl syntax just saying good morning to llama2 and receiving output?

**Comment by borzunov** [comment]
Hi @bitcoinmeetups, here it is:

`curl -X POST "https://chat.petals.dev/api/v1/generate" -d "model=meta-llama/Llama-2-70b-chat-hf" -d "inputs=Once upon a time," -d "max_new_tokens=20"`

This return the following outputs for me:

```json
{"ok":true,"outputs":" there was a young woman named Sophia who lived in a small village nestled in the rolling hills"}
```

Make sure the Llama-2-70b-chat-hf model is healthy (= has enough servers) at https://health.petals.dev/ before running it.

Let me know if you have any other questions!
