### ISSUE TITLE
ModelInfo.__init__() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by Webifi** [petals-infra/chat.petals.dev#40]
Trying to use ModelInfo(repo="petals-team/StableBeluga2", name="stabilityai/StableBeluga2") in my chat.petals.dev colab, I'm getting:

ModelInfo(repo="petals-team/StableBeluga2", name="stabilityai/StableBeluga2")
TypeError: ModelInfo.__init__() got an unexpected keyword argument 'name'

**Comment by borzunov** [comment]
Hi @Webifi,

Please update the code to the latest version - the `name` field was recently added to the `ModelInfo` class in `config.py` and to `app.py`. It seems that you didn't update the `ModelInfo` class to catch up with latest changes.

Hope this helps, let me know if you have other issues!
