### ISSUE TITLE
Cpufeature requirement not allowing backend access of petals

### ISSUE THREAD

**Issue by RPD123-byte** [petals-infra/chat.petals.dev#42]
Every time I run this code:
`git clone https://github.com/petals-infra/chat.petals.dev.git
cd chat.petals.dev
pip install -r requirements.txt
flask run --host=0.0.0.0 --port=5000`
I get this error
 from cpufeature import CPUFeature
ModuleNotFoundError: No module named 'cpufeature'
If I then run `pip install cpufeature`
I get this error.   
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cpufeature
  Running setup.py clean for cpufeature
Failed to build cpufeature
ERROR: Could not build wheels for cpufeature, which is required to install pyproject.toml-based projects
I've tried upgrading and reinstallng pip, setuptools, and wheel. I've tried reinstalling. I've tried changing my virtual environment so no other packages would have a conflict and interfere. How can I get past this?

**Comment by borzunov** [comment]
Hi @RPD123-byte, sorry for the delayed response.

I've fixed this in e5e62f7c0a5cb55b7d87ae0b1cfc2e0f39af01b7. Please pull this commit and try again (you don't have to install `cpufeature`).
