### ISSUE TITLE
[Firefox only] SyntaxError: JSON.parse: unexpected character at line 51 column 73 of the JSON data 

### ISSUE THREAD

**Issue by tiero** [petals-infra/chat.petals.dev#46]
You can replicate it navigating to the endpoint https://health.petals.dev/api/v1/state with a Firefox browser

**Comment by borzunov** [comment]
Hi @tiero,

Let's track this issue here since it's related to the health monitor (not to the chat app): https://github.com/petals-infra/health.petals.dev/issues/16
