### ISSUE TITLE
Server don't stop properly, hangs indefinitely

### ISSUE THREAD

**Issue by slush0** [petals-infra/chat.petals.dev#8]
When I run the daemon and then stops it with keyboard interrupt, server stops responding, but the port is kept occupied by hanging worker thread. This prevents the app to start again, throwing error:

```
$ gunicorn app:app --bind localhost:8004 --threads 5 --timeout 900
....
[2023-01-22 11:09:02 +0000] [357078] [ERROR] Connection in use: ('localhost', 8004)
[2023-01-22 11:09:02 +0000] [357078] [ERROR] Retrying in 1 second.
```

Netstat shows gunicorn, but the process is already killed:
```
$ netstat -anp | grep 8004
tcp        0      0 127.0.0.1:8004          0.0.0.0:*               LISTEN      357022/gunicorn: wo 
tcp        0      0 127.0.0.1:8004          0.0.0.0:*               LISTEN      176873/gunicorn: wo 
```

And yes, ps aux displays hanging worker thread:
```
$ ps aux | grep 357022
dev       357022  0.0  0.4 2980364 289556 pts/4  S    11:08   0:00 gunicorn: worker [app:app]
```

Changing the port works and the server is starting. But I have already like 20 ports occupied by zombie threads :-).

**Comment by borzunov** [comment]
Hi @slush0!

I believe this is a gunicorn issue, that is also present when you run any other app with gunicorn.

I would recommend to use the Flask development server during development, it handles KeyboardInterrupt well:

`flask run --host=0.0.0.0 --port=5017`

I will update the readme to mention that.

In production, I run gunicorn in production as a systemd service by putting this file to `/etc/systemd/system/petals-chat.service`:

```ini
[Unit]
Description=Petals Chat
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=1
User=borzunov
WorkingDirectory=/home/borzunov/chat.petals.ml
ExecStart=/home/borzunov/.local/bin/gunicorn app:app --bind 0.0.0.0:80 --threads 100 --timeout 120 --access-logfile access.log
RemoveIPC=no
KillSignal=SIGKILL

[Install]
WantedBy=multi-user.target
```

This way, you can start/restart/stop the app using these commands:

```bash
sudo systemctl start petals-chat
sudo systemctl restart petals-chat
sudo systemctl stop petals-chat
```

The restart/stop command kill all the subprocesses without leaving zombies. You can also enable the service to be started after reboot:

```bash
sudo systemctl enable petals-chat
```

**Comment by slush0** [comment]
Thank you for your answer! Yes using flask seems to be working well. I suppose that changing README would fix this issue.
